### ISSUE TITLE
Create a WASM transform

### ISSUE THREAD

**Issue by benbromhead** [shotover/shotover-proxy#108]
Using either something like:

- A lib like wasmer https://wasmer.io/posts/wasmer-2.0
- Or the way Timber IO implemented WASM support https://github.com/timberio/vector/blob/41d90b7df1995429d179c89a4f1c176d72a263f1/rfcs/2020-04-15-wasm-plugins.md

Create a Transform that will pass a Wrapper struct into a user defined WASM function, and also allow the user to call `call_next_transform` on it to run subsequent transforms. 

Initially a basic implementation of the Transform config will look something like:

```yaml
- WASMTransform:
   - path: myfunction.wasm
   - name: Func
```
