### ISSUE TITLE
shotover raft investigation

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#1218]
WIP.

There are two places shotover would benefit from cross-instance communication:
* Improved load balancing
* Simplified horizontal scaling

This issue addresses only "Simplified horizontal scaling" but our design should leave open the possibility for "Improved load balancing" to be added later

An investigation into what cross-instance communication could look like for shotover
A quick look at paxos vs raft says that raft is the simpler one of the two, so I'll start there.
I found this crate https://github.com/ritelabs/riteraft which builds higher level abstractions upon this crate https://github.com/tikv/raft-rs
Both seem to be unmaintained though :/

## Transform API design

Transforms will need to send their own custom data across raft.
Say for example CassandraSinkCluster needs to know the data_center, rack and host_id of all shotover nodes in the cluster. Currently this is all hardcoded into the config.

```yaml
    - CassandraSinkCluster:
        first_contact_points: ["172.16.1.2:9044", "172.16.1.3:9044"]
        local_shotover_host_id: "2dd022d6-2937-4754-89d6-02d2933a8f7a"
        shotover_nodes:
          - address: "127.0.0.1:9042"
            data_center: "dc1"
            rack: "rack1"
            host_id: "2dd022d6-2937-4754-89d6-02d2933a8f7a"
        connect_timeout_ms: 3000
```

As such I propose that transforms should be given an internal shotover API from which they can communicate over raft.
TODO: writeup internal API design.

## User facing design

From the users perspective, the transforms would have to be responsible for configuring the use of raft.
For example, we have the following topology.yaml

```yaml
sources:
  cassandra_prod:
    Cassandra:
      listen_addr: "127.0.0.1:9042"
chain_config:
  main_chain:
    - CassandraSinkCluster:
        first_contact_points: ["172.16.1.2:9042", "172.16.1.3:9042"]
        local_shotover_host_id: "2dd022d6-2937-4754-89d6-02d2933a8f7a"
        shotover_nodes:
          - address: "127.0.0.1:9042"
            data_center: "dc1"
            rack: "rack1"
            host_id: "2dd022d6-2937-4754-89d6-02d2933a8f7a"
          - address: "127.0.0.2:9042"
            data_center: "dc1"
            rack: "rack2"
            host_id: "3c3c4e2d-ba74-4f76-b52e-fb5bcee6a9f4"
          - address: "127.0.0.3:9042"
            data_center: "dc1"
            rack: "rack3"
            host_id: "fa74d7ec-1223-472b-97de-04a32ccdb70b"
        connect_timeout_ms: 3000
source_to_chain_mapping:
  cassandra_prod: main_chain
shotover_nodes_raft_clustering:
   - "127.0.0.1:1000"
   - "127.0.0.2:1000"
   - "127.0.0.3:1000"
```

We could have it such that raft capable transforms automatically enter raft mode when `shotover_nodes_raft_clustering` is enabled.
In the above example this would mean that non-local nodes specified in shotover_nodes are redundant.
So maybe we would be better off having them manually specify raft mode like this:

```yaml
sources:
  cassandra_prod:
    Cassandra:
      listen_addr: "127.0.0.1:9042"
chain_config:
  main_chain:
    - CassandraSinkCluster:
        first_contact_points: ["172.16.1.2:9042", "172.16.1.3:9042"]
        raft_enabled_shotover_node:
          - address: "127.0.0.1:9042"
            data_center: "dc1"
            rack: "rack1"
            host_id: "2dd022d6-2937-4754-89d6-02d2933a8f7a"
        connect_timeout_ms: 3000
source_to_chain_mapping:
  cassandra_prod: main_chain
shotover_nodes_raft_clustering:
   - "127.0.0.1:1000"
   - "127.0.0.2:1000"
   - "127.0.0.3:1000"
```

Maybe at this point, to avoid a soup of optional fields, we would be better off having it as an entirely separate transform?
