### ISSUE TITLE
KafkaSinkCluster is rack aware

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#1526]
KafkaSinkCluster needs to follow the same rack aware model as CassandraSinkCluster as we want to use it for the same use case.

## Extended shotover nodes config

The config needs to be extended to:
```yaml
        - KafkaSinkCluster:
            shotover_nodes:
              - address: "172.16.1.100:9042"
                rack: "rack0"
                broker_id: 0
              - address: "172.16.1.101:9042"
                rack: "rack1"
                broker_id: 1
              - address: "172.16.1.102:9042"
                rack: "rack2"
                broker_id: 2
            local_shotover_broker_id: 0
            first_contact_points: ["172.16.1.2:9092"]
            connect_timeout_ms: 3000
```

## Rack aware routing 

We already have fairly good routing in place, requests are sent to the nodes that can handle them.
But the routing needs to be adjusted to favor nodes within the rack that the shotover node is representing.

The rack of each broker can be obtained from the Metadata queries that we are already processing.

## Message rewriting

And the message rewriting needs to be completely redone.
* the Metadata message needs to list all of the shotover nodes.
    + currently it just rewrites addresses to known shotover nodes and deletes duplicates - this turned out to be very fragile and I'll be glad to be rid of it.
* The DescribeCluster message needs to list all of the shotover nodes
* the FindCoordinator message needs to find a shotover node to report the coordinator as by fetching the rack of the coordinator and then mapping that to a shotover node.
