### ISSUE TITLE
Kafka SASL SCRAM support

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#1575]
I'm still gathering information on this, but this writeup is my current understanding:

To support plain SASL in KafkaSinkCluster we capture the SASL requests and replay them every time we open a new connection. This works great for plain SASL.
However when we attempt this with SCRAM SASL, the replayed SASL requests fail since SCRAM is specifically designed to prevent replay attacks.
So, in order to support SCRAM we will need to terminate and restart SASL within KafkaSinkCluster.

I think the configuration would look like:

```yaml
---
sources:
  - Kafka:
      name: "kafka"
      listen_addr: "127.0.0.1:9192"
      chain:
        - KafkaSinkSingle:
            destination_port: 9092
            connect_timeout_ms: 3000
            sasl_scram_credentials:
              - user: username
                pass: password
              - user: admin
                pass: adminpass
```

The following will occur if a SASL SCRAM message is sent:

* SASL requests will be forwarded to a specific destination as usual. This will be how we check the client is authenticated. If we encounter an auth failure here terminate the connection to prevent the client from sending requests with the credentials stored in shotover config.
* the kafka sink will rewrite the final SCRAM request to be regenerated from the username, password, server nonce, server salt and server iteration count.

All non SCRAM SASL messages will be passed through untouched regardless of any config.
