### ISSUE TITLE
gocql client hangs when connecting  to Cassandra via Shotover. The client hangs if a keyspace is specified

### ISSUE THREAD

**Issue by jarodabeysinghe28** [shotover/shotover-proxy#1793]
## Describe the bug
gocql client hangs when connecting  to Cassandra via Shotover. The client hangs if a keyspace is specified

## To Reproduce
Use gocql client and specify a keyspace using

cluster.Keyspace = "keyspace1"

If you use comment out cluster.Keyspace. The client is able to connect successfully.

## Configuration
```yaml
---
main_log_level: "info,shotover_proxy=info"
observability_interface: "0.0.0.0:9001"
```

### Topology
```yaml
sources:
- Cassandra:
    name: privatelink_chain
    listen_addr: 0.0.0.0:6001
    connection_limit: 3000
    tls: {certificate_path: <cert>, private_key_path: <privatekey path>}
    chain:
    - DebugPrinter
    - CassandraSinkCluster:
        first_contact_points: ['10.1.50.50:9042']
        shotover_nodes:
        - {address: '10.0.103.7:6002', data_center: DATACENTRE_1, rack: us-east-1b,
          host_id: <id 1>}
        - {address: '10.0.147.128:6003', data_center: DATACENTRE_1, rack: us-east-1c,
          host_id: <id 2>}
        - {address: '10.0.43.236:6001', data_center: DATACENTRE_1, rack: us-east-1a,
          host_id: <id 3>}
        connect_timeout_ms: 3000
        local_shotover_host_id: <shotover host id>
        tls: {certificate_authority_path: <cert path>,
          verify_hostname: false}

```

## Expected behaviour
The gocql client should connect to Cassandra without hanging

## Systems and Version:
 - OS - Debian 11.10
 - Shotover Version - 0.4.1
 - Cassandra 4.0.13, 5.0.2

## Additional context
Tested on 4.0.13 and 5.0.2 versions of Cassandra
