### ISSUE TITLE
ValkeyLDAPAuth transform

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#1881]
To enable valkey users+ACL to be defined in LDAP a new valkey specific transform will be implemented.
The LDAP group is mapped to ACL strings via configuration stored in shotover.

The transform configuration will look like this:
```yaml
ValkeyLDAPAuth:
  ldap_address: "192.168.0.1:636"

  # control user is used by shotover to create a unique valkey user per ldap user
  valkey_control_user_name: "shotover_control_user"
  valkey_control_user_pass: "hunter2"

  # The name of the LDAP directory to fetch user entries from.
  ldap_directory_for_valkey_users: "ou=user,dc=example,dc=org"
  # The name of the LDAP attribute in the users entry that contains the groups the user belongs to.
  ldap_name_for_group_attribute: "memberOf"
  # Map the groups retrieved from LDAP at ldap_name_for_group_attribute into valkey ACL strings.
  # The resulting ACL strings are concatenated into a single string with whitespace in between.
  map_group_to_valkey_acl:
    map:
      # If the group is "developer" the ACL string becomes "+SET"
      developer: "+SET"
      production: "+GET"

    # If no group is matched, fail authentication.
    fallback: Fail
    
    # Alternatively:
    # If no group is matched, provide a fallback ACL string.
    # fallback:
    #   SucceedWithConstant:
    #     "+GET"

    # Alternatively:
    # If no group is matched, use the group directly as an ACL string.
    # This is most useful with an empty `map` to directly specify the ACL string in LDAP
    # fallback: SucceedWithPassthrough
```

When an AUTH or HELLO request passes through the transform, the following auth process is performed:
1. Extract the user and pass from the request.
2. Perform an LDAP bind with the user and pass from the request.
    * If the bind fails, abort auth process and return an error response to the valkey client.
3. Use the bound ldap connection to query the users group from their entry, 
    * group field name is taken from `ldap_name_for_valkey_acl` transform config
    * user directory is from `ldap_directory_for_valkey_users` transform config
    * [while researching](https://community.spiceworks.com/t/can-any-domain-user-view-active-directory-users-and-computers/401505) I've found that users should be able to query their own entry. So permissions wise this should work fine.
4. Map the users group to a valkey ACL string as configured in the `map_group_to_valkey_acl` transform config
5. add/reset the user in valkey via `ACL SETUSER $USER $ACL_STRING <$PASSWORD`, which works regardless of if a user with that name exists yet.
    * The `$USER` is the username in the request
    * The `$ACL_STRING` is the mapped ACL string from step 4
    * The `$PASSWORD` is randomly generated and held onto by shotover for as long as shotover is running.
        * While shotover is running this password will be reused for this user.
        * On shotover reboot a new password will be generated.
        * The expectation is shotover will be running on the same instance as valkey, so password rotation is not needed.
6. Rewrite the password in the AUTH/HELLO request to use the valkey password that shotover generated for that account and send the request to valkey.

Automated integration tests should be written against openldap.
But we need to manually test against an Active Directory setup at some point.

During local testing, I observed that clustered valkey instances each have their own independent users, so each shotover instance can setup valkey users as it pleases without needing to coordinate with other shotover instances.
However, this transform will only be compatible with ValkeySinkSingle and does not support usage with ValkeySinkCluster.
This is because, to support ValkeySinkCluster, each shotover instance will not be able to connect to other valkey instances since the user is created on only one valkey instance with a password known only to a single shotover instance.

## Chunking

Complete the following as distinct PRs.

1. Implement ValkeyLDAPAuth transform behind alpha-transforms flag
    + Implement transform configuration. Do not use the config for anything yet.
    + Do not implement any of the query rewriting or LDAP connection functionality yet.
    + Include integration test that spins up openLDAP instance, valkey and shotover with the transform. Include a basic test case to set and get a valkey key.
2. Implement steps 1 and 2 of auth process
    + Perform LDAP bind via https://github.com/inejge/ldap3
    + setup integration test such that:
        + there is a valkey user with the same user+pass as the LDAP user, so the test will pass.
        + openLDAP is configured with [msuser](https://github.com/openldap/openldap/blob/master/servers/slapd/schema/msuser.schema) so that it acts like active directory
    + Implement integration test cases:
        + where auth succeeds (LDAP credentials are correct) - run full test suite on this connection
        + where auth fails due to incorrect LDAP password
3. Implement steps 5 and 6 of auth process
   + Set ACL string to permissive dummy value so that tests will pass.
   + Remove valkey username with same name
   + Add test case that fails due to incorrect LDAP username
4. Implement steps 3 and 4 of auth process
   + `map_group_to_valkey_acl.fallback` only supports `Fail` for now
   + Add thorough integration testing for the ACL string mapping edge cases
5. Manual testing against active directory

There is unfortunately no room for parallelization of work here.
