### ISSUE TITLE
Valkey pubsub connection gets stuck when unsubscribing from multiple channels

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#1884]
## Describe the bug

according to the [docs](https://valkey.io/commands/unsubscribe/) UNSUBSCRIBE may have 0 or more responses.
But shotover expects there to be exactly one response.
This results in the connection getting stuck.

More specifically, run the following commands to reproduce:
```
subscribe s1
subscribe s2
unsubscribe
```

the driver sends ["UNSUBSCRIBE"] and then valkey responds with two separate messages:
["unsubscribe", "s2"]
["unsubscribe", "s1"]
And the [implementation](https://github.com/shotover/shotover-proxy/blob/2f7618b65c82c44c2f61caa8417c4027713aff26/shotover/src/codec/valkey.rs#L165) expects only 1 response resulting in the connection getting stuck.

I think the best way to fix this is we need to rewrite the `Decoder::decode` implementation to follow the `is_subscription_message` approach. Probably create a `ResponseType` enum to track the message type instead of a boolean.

### Topology
```yaml
sources:
  - Valkey:
      name: "valkey"
      listen_addr: "127.0.0.1:6379"
      chain:
        - ValkeySinkSingle:
            remote_address: "127.0.0.1:1111"
            connect_timeout_ms: 3000
```

The rust `redis` crate will automatically run `unsubscribe` when a sync pubsub connection is dropped making this really easy to hit.
The async pubsub connection does not do this however, which is how we failed to notice this before.
