### ISSUE TITLE
Redis ConsistentScatter - Some commands result in connection timeout

### ISSUE THREAD

**Issue by corymurphy** [shotover/shotover-proxy#535]
## Is your feature request related to a problem? Please describe.
I'm not sure if this should be a feature request or bug, since this might not be the intended use case for shotover, so please let me know if I'm not using it as intended. This project looks really promising and I like many of the features!

I'm attempting to implement a zero-downtime migration for redis, following [this blog post](https://engblog.nextdoor.com/data-migrations-dont-have-to-come-with-downtime-eabc15893700). The concept is that you use a proxy to mirror all writes, but only read from a single instance until the two instances are at a consistent state, allowing you to transparently to the new instance without downtime.

I tried to use envoy proxy, but they don't support the MULTI redis command used for transactions. We're using redis primarily for Sidekiq, which uses this command, making it difficult to replace those commands like the blog recommends.

I've configured my Sidekiq instance to use shotover as a proxy for 2 AWS Elasticache Redis instances, which is working great for simple commands such as `GET` and `SET`.

I'ved tested this on `0.1.1` using the included dockerfile running on kubernetes. 

## Describe the solution you'd like
My hope is to support commands that Sidekiq uses without timing out. `INFO` command just times out. I enabled the `DebugPrinter`, which shows that the command is getting a response, but it never returns to the client. Looking at the shotover logs just hangs after printing out the results from the INFO command.

```shell
redis-cli -u redis://localhost:6379/0 info
```

Sidekiq also uses the `SADD` and `LPUSH` commands on startup, both of which are timing out the same way as `INFO`.

```
SADD queues default
LPUSH queue:default
```

## Describe alternatives you've considered
I've attempted to adjust the QueryTypeFilter and the read_consistency, but i'm still getting a timeout.

## Additional context

```yaml
# my topology file
---
sources:
  redis_prod:
    Redis:
      listen_addr: "0.0.0.0:6379"
chain_config:
  redis_chain:
    - ConsistentScatter:
        write_consistency: 2
        read_consistency: 1
        route_map:
          one:
            - DebugPrinter
            - RedisTimestampTagger
            - RedisSinkSingle:
                remote_address: aws-elasticache-1:6379
          two:
            - DebugPrinter
            - RedisTimestampTagger
            - QueryTypeFilter:
                filter: Read
            - RedisSinkSingle:
                remote_address: aws-elasticache-2:6379
source_to_chain_mapping:
  redis_prod: redis_chain

````
