### ISSUE TITLE
Redis ConsistentScatter `psubscribe` breaks any subsequent commands

### ISSUE THREAD

**Issue by corymurphy** [shotover/shotover-proxy#537]
## Describe the bug
If you run the `psubscribe` command, then run any other command, the proxy seems to be stuck and no subsequent commands work. Every subsequent command returns the following...

```
ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context
```

## To Reproduce
1. Start shotover
2. Run `redis-cli -u redis://localhost:6379/0 psubscribe sidekiq:config` 
3. Open a new terminal
4. Run `redis-cli -u redis://localhost:6379/0 info` (or any command)

### Topology
```
---
sources:
  redis_prod:
    Redis:
      listen_addr: 0.0.0.0:6379
chain_config:
  redis_chain:
    - ConsistentScatter:
        write_consistency: 2
        read_consistency: 2
        route_map:
          one:
            - DebugPrinter
            - RedisTimestampTagger
            - RedisSinkSingle:
                remote_address: aws-elasticache-instance-1
          two:
            - DebugPrinter
            - RedisTimestampTagger
            - QueryTypeFilter:
                filter: Read
            - QueryTypeFilter:
                filter: PubSubMessage
            - RedisSinkSingle:
                remote_address: aws-elasticache-instance-2
source_to_chain_mapping:
  redis_prod: redis_chain

```

Please include any configuration for setting up services such as `docker-compose` that the `topology.yaml` depends on.

## Expected behaviour
I would expect the redis psubscribe command to have the same behavior as connecting directly to the redis instance. I should be able to run other commands after subscribing.

Please include any configuration for setting up services such as `docker-compose` that the `topology.yaml` depends on.
ame way it behaves when I directly connect to a redis instance.

## Systems and Version:
 - ubuntu 20.04
 - 0.1.1 (i've also tested this on the head of the main branch) 
 - Version of 3rd party software e.g. Cassandra, Redis
     - redis-cli 5.0.14
     - redis server in aws elasticache 5.0.3

## Additional context
n/a
