### ISSUE TITLE
Redis - CLIENT SETNAME behaves incorrectly

### ISSUE THREAD

**Issue by johndelcastillo** [shotover/shotover-proxy#605]
## Describe the bug
The CLIENT SETNAME command it sent to all nodes, and the response is concatenated to the client, which breaks some client libraries. 
Jedis at this stage is confirmed to not be working.

## To Reproduce
shotover-proxy.0afaa9ad7f664117babac37425a07b0d.cu.dev.instaclustr.com:6378> CLIENT SETNAME hello
1) OK
2) OK
3) OK

## Configuration
DR Chain is set, but I can't confirm if it matters

### Topology
3 node DC + 3 node dc in DR

```yaml
sources:
  redis_prod:
    Redis: {batch_size_hint: 4, listen_addr: '0.0.0.0:6378', connection_limit: 20000,
      hard_connection_limit: true}
chain_config:
  redis_chain:
  - Tee:
      behavior: Ignore
      buffer_size: 10000
      chain:
      - QueryTypeFilter: {filter: Read}
      - Coalesce:
          max_behavior:
            CountOrWait: [2000, 100]
      - Tee:
          buffer_size: 100
          timeout_micros: 10000
          chain:
          - QueryCounter: {name: DR_chain}
          - RedisSinkCluster:
              first_contact_points: ['44.232.82.142:6379']
      - 'Null'
  - QueryCounter: {name: Main_chain}
  - RedisClusterPortsRewrite: {new_port: 6378}
  - RedisSinkCluster:
      first_contact_points: ['3.216.108.90:6379']
source_to_chain_mapping: {redis_prod: redis_chain}
```

Please include any configuration for setting up services such as `docker-compose` that the `topology.yaml` depends on.

## Expected behaviour
3.216.108.90:6379> client setname goo
OK

## Systems and Version:
 - OS - Debian buster
 - Shotover Version - 0.1.2
 - Redis 6.0.9
