### ISSUE TITLE
TLS proxy to AWS Keyspaces

### ISSUE THREAD

**Issue by vittoriocanilli** [shotover/shotover-proxy#708]
## Is your feature request related to a problem? Please describe.
Hello,

I have a PHP third-party application, which needs to access a Cassandra keyspace and it does not support TLS connections; I have set up a Cassandra keyspace in AWS Keyspaces, which requires TLS connections: therefore I need to set up a kind of proxy.

After that I have followed these [instructions](https://docs.aws.amazon.com/keyspaces/latest/devguide/programmatic.cqlsh.html), I managed successfully to connect to my Cassandra keyspace on AWS Keyspaces locally via `cqlsh`.

While I was looking for a solution, I have found Shotover proxy, but I am not sure if it is the right one for my issue. Has somebody else tested this proxy solution with AWS Keyspaces already? Thanks in advance.

## Describe the solution you'd like
The PHP third-party application is running in a Kubernetes container, which has a [ProxySQL](https://hub.docker.com/r/proxysql/proxysql) side container: ProxySQL accepts MySQL insecure MySQL connections from localhost (the PHP application, not able to support secure MySQL connections) and forwards them as secure MySQL connections to the database in AWS RDS.

With Shotover I would like to implement a proxy in a new side container, which does for the Cassandra connections what the ProxySQL side container does for the MySQL connections.

## Describe alternatives you've considered
I have searched for similar proxy solutions, but I did not find any yet. The support of the PHP third-party application could not disclose when and if any support to secure Cassandra connections will be given. AWS support did not provide a solution yet.

## Additional context
It would be nice to have an example with a Dockerfile where the necessary environment variables are passed in order to have such a proxy running.

**Comment by benbromhead** [comment]
Thanks for the feedback @vittoriocanilli - you _should_ be able to acheive what you are looking for here be using this example configuration https://github.com/shotover/shotover-proxy/blob/main/shotover-proxy/example-configs/cassandra-tls/topology.yaml

You will just need to remove the tls config from the source to turn off TLS:


```yaml
...
sources:
  cassandra_prod:
    Cassandra:
      listen_addr: "127.0.0.1:9043"
...

```

We publish a docker image of shotover here - https://hub.docker.com/r/shotover/shotover-proxy/tags 

Currently the docker image doesn't support environment variable style config, so you will need to bind mount a config volume or if you are using something like kubernetes use a config map to inject the topology.yaml file in. You'll also need to provide the AWS Keyspaces certificates (you can grab them using the documentation for keyspaces here in the first few steps of the java driver setup https://docs.aws.amazon.com/keyspaces/latest/devguide/using_java_driver.html) 

You'll use the keyspaces endpoint as well `cassandra.us-east-2.amazonaws.com`

**Comment by vittoriocanilli** [comment]
Thanks for the reply @benbromhead - I have created a Docker file as follows:

```
FROM shotover/shotover-proxy:v0.1.4

COPY files/cassandra_proxy/config.yaml /config/
COPY files/cassandra_proxy/topology.yaml /config/

ADD https://certs.secureserver.net/repository/sf-class2-root.crt /config/

#ENTRYPOINT ["./shotover-proxy"]
```

The certificate is taken from the [AWS documentation](https://docs.aws.amazon.com/keyspaces/latest/devguide/programmatic.cqlsh.html).

This is the _config.yaml_ file: 
```
---
main_log_level: "info,shotover_proxy=info"
observability_interface: "0.0.0.0:9001"
```
and this is the _topology.yaml_ file: 
```
---
sources:
  cassandra_prod:
    Cassandra:
      listen_addr: "127.0.0.1:9042"
chain_config:
  main_chain:
    - CassandraSinkSingle:
        remote_address: "cassandra.eu-west-1.amazonaws.com:9142"
        tls:
          certificate_path: "/config/sf-class2-root.crt"
source_to_chain_mapping:
  cassandra_prod: main_chain
```

I manage to build the container successfully, but when I try to run it, I get this error:
```

Error: chain_config.main_chain[0].CassandraSinkSingle.tls: missing field `certificate_authority_path` at line 12 column 27
```

So I edited the _topology.yaml_ file to use the certificate even as certificate authority:
```
---
sources:
  cassandra_prod:
    Cassandra:
      listen_addr: "127.0.0.1:9042"
chain_config:
  main_chain:
    - CassandraSinkSingle:
        remote_address: "cassandra.eu-west-1.amazonaws.com:9142"
        tls:
          certificate_authority_path: /config/sf-class2-root.crt"
          certificate_path: "/config/sf-class2-root.crt"
source_to_chain_mapping:
  cassandra_prod: main_chain
```

but then in run time I get this error message instead:
```
Error: chain_config.main_chain[0].CassandraSinkSingle.tls: missing field `private_key_path` at line 11 column 37
```

And if I keep just the certificate authority, I get this other error instead:
```
Error: chain_config.main_chain[0].CassandraSinkSingle.tls: missing field `certificate_path` at line 11 column 37
```

So it looks like Shotover needs all 3 of them: _certificate_authority_path_, _certificate_path_ and _private_key_path_. As I have only a certificate and no key, how can I proceed in this case? Thanks in advance.
