### ISSUE TITLE
CassandraSinkCluster design

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#712]
## Motivation:

Unlike redis, a queried cassandra node will become a coordinator node and will fetch the results of your query from another node if needed.
So we dont technically need a CassandraSinkCluster.
However a CassandraSinkCluster is critical for:
* performance - relying on a single destination node introduces an extra hop between nodes for every query. We can avoid that by performing token aware routing to directly query the concerned node.
* robustness - if our single destination node goes down we need to be able to fallback to other nodes

for building and maintaining the topology we could either:
* use the gossip protocol
* just query system.peers_v2 + subscribe to StatusChange events

## gossip protocol

* by default we get all information that a cassandra node would have
* there might be weird unexpected consequences of us pretending to be a cassandra node
* need to implement an entirely new protocol:
    + is it even documented?
    + is it even stable between versions?

## query/events protocol

* if we subscribe to status changes on a node and the node dies then we may not notice that we are no longer getting node updates
    + we could alleviate this by doing a heartbeat query every 10s or by running the same subscription on multiple nodes
    + is there an in between failure state where the node is alive but is disconnected from the rest of the cluster?
* easier to configure network - only need to configure 1 port instead of 2

### transform config

```yaml
- CassandraSinkCluster
    # The nodes that shotover will attempt to connect to when shotover is started in order to discover every other node.
    # Only one of these needs to be accessible for shotover initialisation to succeed.
    # Once shotover is initialized these nodes can go down without consequences,
    # but when shotover is restarted at least one of these nodes must be accessible.
    first_contact_points: ["127.0.0.1:2220", "127.0.0.1:2221"]

    # Specify the name of the datacenter that messages will be routed to.
    # Messages will never be routed outside of this datacenter even if all replicas within the datacenter are down.
    # The specified first_contact_points must belong to this data center.
    datacenter: "dc1"

    # When this field is provided TLS is used when connecting to the remote instances.
    # Removing this field will disable TLS.
    tls:
      # Path to the certificate authority file, typically named with a .crt extension.
      certificate_authority_path: "example-configs/cassandra-tls/certs/localhost_CA.crt"
      # Path to the certificate file, typically named with a .crt extension.
      certificate_path: "example-configs/cassandra-tls/certs/localhost.crt"
      # Path to the private key file, typically named with a .key extension.
      private_key_path: "example-configs/cassandra-tls/certs/localhost.key"

```

### Building and maintaining topology map

at boot:
1. build topology by querying system.peers_v2 on a first_contact_points node
2. subscribe to status changes on that node to keep the topology up to date

If any failure indicating a down node occurs when delivering a message, remove the node from our topology and rerun the topology building process on another known node within the same DC.
This will protect against the case where our topology node silently goes down without us noticing and therefore silently preventing us from getting status changes.

Cassandra clusters are not dependent on the seed nodes existing when rebooting an instance as they persist topology state to the file system.
We could do the same here but:
* it would be the first time shotover relies on mutable fs storage for anything.
* the datastax driver does not appear to do that

So lets not do that.

This has some interesting logic: core/src/main/java/com/datastax/oss/driver/internal/core/metadata/NodeStateManager.java
SUGGEST_UP is triggered from a StatusChange up message

### Routing and load balancing

MVP:
Implement token aware routing, when there are multiple replicas of the same node pick one at random.
If the selected node fails, keep trying replica nodes within the same DC until we find one that works.

Once this is implemented, we can extend our load balancing to use the "power of two random choices" algorithm described here:
https://www.datastax.com/blog/improved-client-request-routing-apache-cassandratm

Also refer to this which explains the reasoning of never sending messages outside of our specified data center:
https://docs.datastax.com/en/developer/java-driver/4.14/manual/core/load_balancing/#local-only

### Authentication

In order to support clusters that use authentication, within a single connection to a client, we will need to:
* When the client sends a AUTH_RESPONSE message that results in an AUTH_SUCCESS from the cassandra instance then store the AUTH_RESPONSE message contents within the transform state.
* When a connection from shotover to cassandra responds with an AUTHENTICATE and we have a stored AUTH_RESPONSE then we should:
    + Shotover should control the entire authentication process, hiding the authentication messages from the client
    + Replay the stored known good AUTH_RESPONSE message.
    + If it fails then return a custom error to the client. (A regular auth error wouldnt make sense, it might just be this one instance that is misconfigured)

Currently shotover does not parse these messages at all so we will need to first add support for that.
