### ISSUE TITLE
RedisSinkCluster does not know of a node containing the required slot

### ISSUE THREAD

**Issue by weixiong-ins** [shotover/shotover-proxy#740]
## Describe the bug
When connected to shotover from a Redis cluster, got the following error
```
➜   redis-cli -c -h 34.230.93.245 -p 6378
34.230.93.245:6378> set name asdf
(error) ERR Shotover RedisSinkCluster does not know of a node containing the required slot
```

## To Reproduce
The bug might be annoying to reproduce.
Shotover crashes as expected if the Redis cluster is completely unformed (“protocol error: empty slot map!“).
The problem is when Shotover starts while the cluster is being formed, when some slots have been assigned but not all.

## Configuration
config.yaml
```
main_log_level: "info,shotover_proxy=info"
observability_interface: "127.0.0.1:9001"
```
### Topology
topology.yaml
```
sources:
  redis_prod:
    Redis: {batch_size_hint: 1000, listen_addr: '0.0.0.0:6378', connection_limit: 3000000}
chain_config:
  redis_chain:
  - RedisClusterPortsRewrite: {new_port: 6378}
  - RedisSinkCluster:
      first_contact_points: ['34.230.93.245:6379']
source_to_chain_mapping: {redis_prod: redis_chain}
```

## Expected behaviour
The error path that returns the “does not know of a node containing the required slot” message needs to trigger the re-fetching of the slot map.

## Systems and Version:
 - OS: debian10
 - Shotover Version: 0.1.4
 - Version of 3rd party software e.g. Redis 7.0.4
