### ISSUE TITLE
Investigating running docker on tmpfs

### ISSUE THREAD

**Issue by rukai** [shotover/shotover-proxy#826]
Locally on my machine I cut 10s off the runtime of `cassandra_int_tests::test_passthrough` by adding the following to `docker-compose.yaml`:
```yaml
    volumes:
      - type: tmpfs
        target: /var/lib/cassandra
```

Will need to test it out on CI though, possibly we dont have enough ram.
We should land https://github.com/shotover/shotover-proxy/pull/825 before attempting this though as it will be easier to measure and will avoid merge conflicts.

Possibly we could do something similar to redis? Maybe it doesnt flush to disk enough for it to help.
